# Generated by Django 4.1.1 on 2022-10-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Обложка')),
                ('title_ru', models.CharField(max_length=256, verbose_name='title russian')),
                ('title_en', models.CharField(max_length=256, verbose_name='title english')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='created data')),
                ('logo', models.ImageField(upload_to='', verbose_name="partner's logo")),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ('-id',),
            },
        ),
    ]
