# Generated by Django 4.1.1 on 2022-10-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='image',
        ),
        migrations.AddField(
            model_name='partner',
            name='link',
            field=models.URLField(default=1, verbose_name='web-site'),
            preserve_default=False,
        ),
    ]
