# Generated by Django 4.1.1 on 2022-11-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_remove_partner_logo_partner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='background'),
        ),
    ]
