# Generated by Django 4.1.1 on 2022-11-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_texts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetext',
            name='type',
            field=models.CharField(choices=[('library', 'Library'), ('Simulation game', 'Simulation Game'), ('Projects', 'Projects'), ('Training', 'Training'), ('Club', 'Club')], max_length=256, verbose_name='service type'),
        ),
    ]
