# Generated by Django 4.1.1 on 2022-11-23 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_location_en_alter_post_location_ru'),
        ('service_texts', '0002_alter_servicetext_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetext',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posttype', verbose_name='service type'),
        ),
    ]
