# Generated by Django 4.1.1 on 2022-10-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('instagram_link', models.URLField(verbose_name='ссылка на инстаграмм пост')),
                ('facebook_link', models.URLField(verbose_name='Ссылка на фейсбук пост')),
            ],
        ),
    ]
