# Generated by Django 4.1.1 on 2022-10-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-id',), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('russian', 'Russian')], default=1, max_length=256),
            preserve_default=False,
        ),
    ]
