# Generated by Django 4.1.1 on 2022-10-06 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('language', models.CharField(choices=[('english', 'English'), ('russian', 'Russian')], max_length=256)),
                ('image', models.ImageField(upload_to='', verbose_name='Обложка')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('facebook', models.URLField(verbose_name='Ссылка на пост в фейсбуке')),
                ('twitter', models.URLField(verbose_name='Ссылка на пост в твиттере')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_us', to='categories.category', verbose_name='навбар')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='NewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.new', verbose_name='новость')),
            ],
            options={
                'verbose_name': 'New Image',
                'verbose_name_plural': 'New Images',
                'ordering': ('-id',),
            },
        ),
    ]
