# Generated by Django 4.1.1 on 2022-10-05 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('english', 'En'), ('russian', 'Ru')], max_length=256)),
                ('image', models.ImageField(upload_to='', verbose_name='Обложка')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'New',
                'verbose_name_plural': 'News',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='NewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.new', verbose_name='новость')),
            ],
            options={
                'verbose_name': 'New Image',
                'verbose_name_plural': 'New Images',
                'ordering': ('-id',),
            },
        ),
    ]
