# Generated by Django 4.1.1 on 2022-10-05 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ('-id',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
