# Generated by Django 4.1.1 on 2022-10-09 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='category',
        ),
        migrations.DeleteModel(
            name='NewImage',
        ),
    ]
