# Generated by Django 4.1.1 on 2022-10-06 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_language'),
        ('news', '0003_alter_new_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='about_us', to='categories.category', verbose_name='навбар'),
            preserve_default=False,
        ),
    ]
