# Generated by Django 4.1.1 on 2022-11-19 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_new_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsocial',
            name='new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_socials', to='news.new'),
        ),
    ]
