# Generated by Django 4.1.1 on 2022-10-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_new_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='facebook',
            field=models.URLField(default=1, verbose_name='Ссылка на пост в фейсбуке'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new',
            name='twitter',
            field=models.URLField(default=2, verbose_name='Ссылка на пост в твиттере'),
            preserve_default=False,
        ),
    ]
