# Generated by Django 4.1.1 on 2022-10-06 21:58

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('language', models.CharField(choices=[('english', 'English'), ('russian', 'Russian')], max_length=256)),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('ordering', models.PositiveSmallIntegerField()),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='categories.category')),
            ],
            options={
                'verbose_name': 'Разделы',
                'verbose_name_plural': 'Раздел',
                'ordering': ('ordering',),
            },
        ),
    ]
