# Generated by Django 4.1.1 on 2022-10-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('ordering',), 'verbose_name': 'Разделы', 'verbose_name_plural': 'Раздел'},
        ),
        migrations.AddField(
            model_name='category',
            name='language',
            field=models.CharField(choices=[('english', 'En'), ('russian', 'Ru')], default=1, max_length=256),
            preserve_default=False,
        ),
    ]
