# Generated by Django 4.1.1 on 2022-10-26 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_category_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
