# Generated by Django 4.1.1 on 2022-11-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_remove_category_level_remove_category_lft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='route',
            field=models.CharField(default=1, max_length=256, verbose_name='endpoint на который должна перекидывать'),
            preserve_default=False,
        ),
    ]
