# Generated by Django 4.1.1 on 2022-11-10 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('surname', models.CharField(max_length=256, verbose_name='surname')),
                ('phone_number', models.CharField(max_length=14, validators=[
                    django.core.validators.RegexValidator(message='You should write +996[code][number]',
                                                          regex='^(\\+996)\\d{9}$')], verbose_name='phone number')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_ru',
                 models.CharField(default='Адрес: ул. Токомбаева 21/2, Бишкек 720000, Кыргызстан ', max_length=256,
                                  verbose_name='Адрес')),
                ('address_en',
                 models.CharField(default='Address: 21/2 Tokombaev str, Bishkek 720000, Kyrgyzstan ', max_length=256,
                                  verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=13, verbose_name='phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Наши Контакты',
                'verbose_name_plural': 'Наши Контакты',
                'ordering': ('-id',),
            },
        ),
    ]
