# Generated by Django 4.1.1 on 2022-10-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='21/2 Tokombaev str, Bishkek 720000, Kyrgyzstan', max_length=256, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=13, verbose_name='phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Наши Контакты',
                'verbose_name_plural': 'Наши Контакты',
                'ordering': ('-id',),
            },
        ),
    ]
