# Generated by Django 4.1.1 on 2022-10-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Кыргызская Республика', max_length=256, verbose_name='Кыргызская Республика')),
                ('some_numbers', models.PositiveIntegerField(verbose_name='720021')),
                ('city', models.CharField(default='г.', max_length=256, verbose_name='Город')),
                ('street', models.CharField(max_length=256, verbose_name='Улица')),
                ('town', models.CharField(max_length=256, verbose_name='Здание')),
                ('at_foot', models.PositiveSmallIntegerField(verbose_name='Этаж')),
                ('entrance', models.CharField(max_length=256, verbose_name='Вход со стороны?')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Тел')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Наши Контакты',
                'verbose_name_plural': 'Наши Контакты',
                'ordering': ('-id',),
            },
        ),
    ]
