# Generated by Django 4.1.1 on 2022-10-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='address',
        ),
        migrations.AddField(
            model_name='contactus',
            name='address_en',
            field=models.CharField(default='Address: 21/2 Tokombaev str, Bishkek 720000, Kyrgyzstan ', max_length=256, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='address_ru',
            field=models.CharField(default='Адрес: ул. Токомбаева 21/2, Бишкек 720000, Кыргызстан ', max_length=256, verbose_name='Адрес'),
        ),
    ]
