# Generated by Django 4.1.1 on 2022-10-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contactus_some_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='at_foot',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='city',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='country',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='entrance',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='some_numbers',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='street',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='town',
        ),
        migrations.AddField(
            model_name='contactus',
            name='adsress',
            field=models.CharField(default='21/2 Tokombaev str, Bishkek 720000, Kyrgyzstan', max_length=256, verbose_name='Адрес'),
        ),
    ]
