# Generated by Django 4.1.1 on 2022-10-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Обложка')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('link', models.URLField(verbose_name='Ссылка')),
            ],
        ),
    ]
