# Generated by Django 4.1.1 on 2022-10-26 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='library',
            name='description_ru',
        ),
    ]
