# Generated by Django 4.1.1 on 2022-10-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_alter_library_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='image',
            field=models.FileField(upload_to='', verbose_name='Обложка'),
        ),
    ]
