# Generated by Django 4.1.1 on 2022-11-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_remove_library_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='background'),
        ),
    ]
