# Generated by Django 4.1.1 on 2022-10-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('language', models.CharField(choices=[('english', 'English'), ('russian', 'Russian')], max_length=256)),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('subtitle', models.CharField(default='О нас', max_length=256, verbose_name='О нас')),
                ('text', models.TextField(verbose_name='О нас')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
                'ordering': ('-id',),
            },
        ),
    ]
