# Generated by Django 4.1.1 on 2022-11-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='background'),
        ),
    ]
