# Generated by Django 4.1.1 on 2022-10-09 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='subtitle',
        ),
    ]
