# Generated by Django 4.1.1 on 2022-11-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_alter_aboutus_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='type',
            field=models.CharField(choices=[('Our mission', 'Our Mission'), ('About Us', 'About Us')], default=1, max_length=256, verbose_name='type'),
            preserve_default=False,
        ),
    ]
