# Generated by Django 4.1.1 on 2022-11-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_aboutus_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='type',
            field=models.CharField(choices=[('our_mission', 'Our Mission'), ('about_Us', 'About Us')], max_length=256, verbose_name='type'),
        ),
    ]
