# Generated by Django 4.1.1 on 2022-12-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_us", "0004_alter_aboutus_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPartners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_ru", models.TextField()),
                ("content_en", models.TextField()),
            ],
            options={
                "verbose_name": "О партнере",
                "verbose_name_plural": "О партнерах",
            },
        ),
        migrations.CreateModel(
            name="AboutTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_ru", models.TextField()),
                ("content_en", models.TextField()),
            ],
            options={
                "verbose_name": "О команде",
                "verbose_name_plural": "О команде",
            },
        ),
    ]
