# Generated by Django 4.1.1 on 2022-10-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='', verbose_name='Логотип')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('title', models.CharField(max_length=256, verbose_name='Название соц. сети')),
            ],
            options={
                'verbose_name': 'Социальные сети',
                'verbose_name_plural': 'Социальные сети',
                'ordering': ('-id',),
            },
        ),
    ]
