# Generated by Django 4.1.1 on 2022-10-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='twitter',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='social',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='social',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='social',
            name='youtube',
        ),
        migrations.AddField(
            model_name='social',
            name='icon',
            field=models.ImageField(default=1, upload_to='', verbose_name='Facebook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social',
            name='title',
            field=models.CharField(default=1, max_length=256, verbose_name='Instagram'),
            preserve_default=False,
        ),
    ]
