# Generated by Django 4.1.1 on 2022-10-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('fullname_ru', models.CharField(max_length=256, verbose_name='fullname russian')),
                ('position_ru', models.CharField(max_length=256, verbose_name='position russian')),
                ('fullname_en', models.CharField(max_length=256, verbose_name='fullname english')),
                ('position_en', models.CharField(max_length=256, verbose_name='fullname english')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('facebook', models.URLField(verbose_name='link facebook account')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команда',
                'ordering': ('-id',),
            },
        ),
    ]
