# Generated by Django 4.1.1 on 2022-10-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='position_en',
            field=models.CharField(max_length=256, verbose_name='position english'),
        ),
    ]
