# Generated by Django 4.1.1 on 2022-11-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='duration_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='duration english'),
        ),
        migrations.AlterField(
            model_name='post',
            name='duration_ru',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='duration russian'),
        ),
    ]
