# Generated by Django 4.1.1 on 2022-11-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_duration_en_alter_post_duration_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='beneficiaries',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='beneficiaries english'),
        ),
        migrations.AlterField(
            model_name='post',
            name='participants_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='participants english'),
        ),
        migrations.AlterField(
            model_name='post',
            name='participants_ru',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='participants russian'),
        ),
        migrations.AlterField(
            model_name='post',
            name='project_goals_en',
            field=models.TextField(blank=True, null=True, verbose_name='Project goals english'),
        ),
        migrations.AlterField(
            model_name='post',
            name='project_goals_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Project goals russian'),
        ),
        migrations.AlterField(
            model_name='post',
            name='target_audience_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Target audience english'),
        ),
        migrations.AlterField(
            model_name='post',
            name='target_audience_ru',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Target audience russian'),
        ),
    ]
