# Generated by Django 4.1.1 on 2022-10-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_game_post_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('SIMULATION GAME', 'Simulation Game'), ('PROJECT', 'Project'), ('DIGITAL SOLUTIONS', 'Digital Solution'), ('TRAININGS', 'Trainings')], default=1, max_length=256),
            preserve_default=False,
        ),
    ]
