# Generated by Django 4.1.1 on 2022-10-26 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_post_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='beneficiaries_en',
            new_name='beneficiaries',
        ),
        migrations.RemoveField(
            model_name='post',
            name='beneficiaries_ru',
        ),
    ]
