# Generated by Django 4.1.1 on 2022-11-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_beneficiaries_alter_post_participants_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='location english'),
        ),
        migrations.AlterField(
            model_name='post',
            name='location_ru',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='location russian'),
        ),
    ]
