# Generated by Django 4.1.1 on 2022-11-06 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=256, verbose_name='title russian')),
                ('title_en', models.CharField(max_length=256, verbose_name='title english')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='created data')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_type', to='posts.posttypes', verbose_name='post type'),
        ),
    ]
