# Generated by Django 4.1.1 on 2022-11-06 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_posttypes_alter_post_post_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostTypes',
            new_name='PostType',
        ),
    ]
