# Generated by Django 4.1.1 on 2022-11-06 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_posttypes_posttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posttype',
            options={'verbose_name': 'Тип поста', 'verbose_name_plural': 'Типы постов'},
        ),
    ]
