# Generated by Django 4.1.1 on 2022-11-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_alter_post_duration_ru"),
    ]

    operations = [
        migrations.AddField(
            model_name="posttype",
            name="value",
            field=models.CharField(default=1, max_length=256, verbose_name="Значение"),
            preserve_default=False,
        ),
    ]
