# Generated by Django 4.1.1 on 2022-11-19 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_posttype_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='project_goals',
            field=models.TextField(default=1, max_length=256, verbose_name='Цели проекта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='target_audience',
            field=models.CharField(default=1, max_length=256, verbose_name='Целевая группа'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NewSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'Youtube')], max_length=256, verbose_name='Социальная сеть')),
                ('link', models.URLField(verbose_name='ссылка на статью')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='posts.post')),
            ],
        ),
    ]
