# Generated by Django 4.1.1 on 2022-11-19 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_project_goals_post_target_audience_newsocial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'Youtube')], max_length=256, verbose_name='Социальная сеть')),
                ('link', models.URLField(verbose_name='ссылка на статью')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_socials', to='posts.post')),
            ],
        ),
        migrations.DeleteModel(
            name='NewSocial',
        ),
    ]
